version: '3.7'

networks:
  server-prod:

services:
  server:
    container_name: api
    build:
      context: ../../
      dockerfile: ./deployment/prod/Dockerfile.prod
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: 'unless-stopped'
    networks:
      - server-prod
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: server-prod
    expose:
      - 5432
    ports:
      - 5433:5432
    restart: 'unless-stopped'
