version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-root}:${DB_PASS:-password}@db:5432/${DB_NAME:-mydb}
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=${DB_USER:-root}
      - PGPASSWORD=${DB_PASS:-password}
      - PGDATABASE=${DB_NAME:-mydb}
      - PORT=${PORT:-3000}
      - TYPESCRIPT_VERSION=5.9.3
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    depends_on:
      - db
    networks:
      - devnet

  db:
    image: postgres:18
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER:-root}
      - POSTGRES_PASSWORD=${DB_PASS:-password}
      - POSTGRES_DB=${DB_NAME:-mydb}
    ports:
      - '${DB_PORT:-5432}:5432'
    networks:
      - devnet

  pgadmin:
    image: dpage/pgadmin4:9.9.0
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-password}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - devnet

volumes:
  postgres-data:
  pgadmin-data:

networks:
  devnet:
