name: pr check

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checking lint
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checking build
        run: pnpm run build

  test-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run E2E Tests
        run: pnpm run test:e2e
